# Generated by Django 3.0 on 2020-10-28 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201027_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='average_pace',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='run',
            name='average_spd',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
