# Generated by Django 3.0 on 2020-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201028_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='average_pace',
            field=models.CharField(default='not calculated', max_length=100),
        ),
    ]
